In [8]:
import requests
import json

url = "https://polisen.se/api/events"

response = requests.get(url)

# Ensure the encoding is set to UTF-8
response.encoding = 'utf-8'

data = response.json()

# Pretty print the JSON data
print(json.dumps(data, ensure_ascii=False, indent=4))

[
    {
        "id": 551370,
        "datetime": "2024-10-03 13:05:20 +02:00",
        "name": "03 oktober 12.55, Stöld, Falun",
        "summary": "Polisen har genomfört en brottsplatsundersökning på en skola i Falun.",
        "url": "/aktuellt/handelser/2024/oktober/3/03-oktober-12.55-stold-falun/",
        "type": "Stöld",
        "location": {
            "name": "Falun",
            "gps": "60.60646,15.6355"
        }
    },
    {
        "id": 551351,
        "datetime": "2024-10-03 13:05:03 +02:00",
        "name": "03 oktober 13.00, Trafikkontroll, Västerbottens län",
        "summary": "Skellefteå och Umeå, ett urval av polisens arbete i trafiken",
        "url": "/aktuellt/handelser/2024/oktober/3/03-oktober-13.00-trafikkontroll-vasterbottens-lan/",
        "type": "Trafikkontroll",
        "location": {
            "name": "Västerbottens län",
            "gps": "65.333731,16.516169"
        }
    },
    {
        "id": 551365,
        "datetime": "2024-10-03 12:55:28 +02:

In [9]:
for event in data:
    print(event['name'])


03 oktober 12.55, Stöld, Falun
03 oktober 13.00, Trafikkontroll, Västerbottens län
03 oktober 13.00, Övrigt, Hallands län
03 oktober 13.00, Övrigt, Västra Götalands län
03 oktober 12.47, Rattfylleri, Örebro
03 oktober 12.18, Trafikolycka, Karlstad
03 oktober 12.30, Trafikkontroll, Norrbottens län
03 oktober 10.33, Rån, Ystad
02 oktober 04.21, Stöld, försök, Umeå
03 oktober 08.01, Arbetsplatsolycka, Österåker
03 oktober 08.12, Trafikolycka, Ljungby
03 oktober 07.14, Sammanfattning natt, Jämtlands län
03 oktober 07.57, Sammanfattning natt, Jönköpings län
03 oktober 06.04, Brand, Västerås
03 oktober 01.32, Brand, Västerås
03 oktober 08.10, Rattfylleri, Hallands län
03 oktober 04.04, Motorfordon, stöld, Söderhamn
03 oktober 08.00, Sammanfattning natt, Södermanlands län
03 oktober 07.56, Sammanfattning natt, Östergötlands län
03 oktober 03.36, Stöld/inbrott, Enköping
03 oktober 00.50, Motorfordon, stöld, Uppsala
03 oktober 07.14, Sammanfattning natt, Jämtlands län
03 oktober 07.10, Sammanfa

In [2]:
name_count = len([event['name'] for event in data if 'name' in event])

print(f"Total number of names: {name_count}")

Total number of names: 0


In [4]:
import numpy as np

print(np.random.randn(20, 3))

[[-0.70910714  0.01548817 -1.54108732]
 [ 0.18225438  0.6928365   0.30389421]
 [-0.15560955 -0.05503013  0.53058604]
 [-0.52595371  0.55616129 -2.14831881]
 [ 0.81704414 -0.96046325  0.82660577]
 [ 0.92292396 -1.45574728 -0.52136522]
 [-0.37961991  0.05430855 -0.5769181 ]
 [-0.46265084 -2.71288461  1.82983393]
 [-0.16851603  0.44270605 -1.18660442]
 [-0.54677374  0.11208957 -0.13579942]
 [ 1.02424676  1.00151324  0.34130559]
 [ 0.66404268  0.05287334  1.75114943]
 [ 0.5078887  -0.60569516  0.06533265]
 [ 0.72403256  2.28951181 -1.39077436]
 [-1.02672345 -2.12298606 -0.69386017]
 [-0.061766   -1.16520425  0.28705324]
 [-1.38127618 -0.26271239 -1.05928357]
 [ 1.33629705  1.19131313  0.00347055]
 [-1.35926603 -0.16954934 -0.71484585]
 [ 1.09595213  1.09018691  0.81642021]]
